# Algoritmos de optimización - Seminario<br>
Nombre y Apellidos:   Rubén Cuenca Carbonell<br>
Url: <br>
Problema:https://github.com/RCuencaOrbita/algoritmos-optimizacion/tree/main/Practica
>1. Sesiones de doblaje <br>

Descripción del problema:<br>
(*) La respuesta es obligatoria





                                        

Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las
tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de
doblaje cobran toda la misma cantidad por cada día que deben desplazarse hasta el estudio de
grabación independientemente del número de tomas que se graben. No es posible grabar más
de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los
servicios de los actores de doblaje sea el menor posible.

|Toma\Actor|1|2|3|4|5|6|7|8|9|10||Total|
|---|---|---|---|---|---|---|---|---|---|---|---|---|
1|1|1|1|1|1|0|0|0|0|0||5
2|0|0|1|1|1|0|0|0|0|0||3
3|0|1|0|0|1|0|1|0|0|0||3
4|1|1|0|0|0|0|1|1|0|0||4
5|0|1|0|1|0|0|0|1|0|0||3
6|1|1|0|1|1|0|0|0|0|0||4
7|1|1|0|1|1|0|0|0|0|0||4
8|1|1|0|0|0|1|0|0|0|0||3
9|1|1|0|1|0|0|0|0|0|0||3
10|1|1|0|0|0|1|0|0|1|0||4
11|1|1|1|0|1|0|0|1|0|0||5
12|1|1|1|1|0|1|0|0|0|0||5
13|1|0|0|1|1|0|0|0|0|0||3
14|1|0|1|0|0|1|0|0|0|0||3
15|1|1|0|0|0|0|1|0|0|0||3
16|0|0|0|1|0|0|0|0|0|1||2
17|1|0|1|0|0|0|0|0|0|0||2
18|0|0|1|0|0|1|0|0|0|0||2
19|1|0|1|0|0|0|0|0|0|0||2
20|1|0|1|1|1|0|0|0|0|0||4
21|0|0|0|0|0|1|0|1|0|0||2
22|1|1|1|1|0|0|0|0|0|0||4
23|1|0|1|0|0|0|0|0|0|0||2
24|0|0|1|0|0|1|0|0|0|0||2
25|1|1|0|1|0|0|0|0|0|1||4
26|1|0|1|0|1|0|0|0|1|0||4
27|0|0|0|1|1|0|0|0|0|0||2
28|1|0|0|1|0|0|0|0|0|0||2
29|1|0|0|0|1|1|0|0|0|0||3
30|1|0|0|1|0|0|0|0|0|0||2
||||||||||||
TOTAL|22|14|13|15|11|8|3|4|2|2||


(*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?<br>



¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones.




Respuesta

In [ ]:

import math
#si no tenemos en cuenta las restricciones, todos los posibles subconjuntos del conjunto de tomas, serían el conjunto potencia
#el cardinal del conjunto potencia es |P|=2^|Tomas|
print('|P|=',2**30)

#Con las restricciones, hay 30 tomas, tendremos que hacer 6 sesiones de 5 tomas
#las combinaciones posibles son C(n, k) = n! / (k! * (n-k)!) (n=30 tomas, k=6 tomas por sesión)
print('C(30,6)=',math.factorial(30)/(math.factorial(6)*math.factorial(30-6)))

|P|= 1073741824
C(30,6)= 593775.0


Modelo para el espacio de soluciones<br>
(*) ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, argumentalo)


Respuesta

In [ ]:
import numpy as np

#Modelo el problema con una matriz de tomas las tomas en filas (x) y los actores en columnas (y). tomas[x][y]=1 El actor 'y' participa en la toma 'x'
tomas=[ \
[1,1,1,1,1,0,0,0,0,0], \
[0,0,1,1,1,0,0,0,0,0], \
[0,1,0,0,1,0,1,0,0,0], \
[1,1,0,0,0,0,1,1,0,0], \
[0,1,0,1,0,0,0,1,0,0], \
[1,1,0,1,1,0,0,0,0,0], \
[1,1,0,1,1,0,0,0,0,0], \
[1,1,0,0,0,1,0,0,0,0], \
[1,1,0,1,0,0,0,0,0,0], \
[1,1,0,0,0,1,0,0,1,0], \
[1,1,1,0,1,0,0,1,0,0], \
[1,1,1,1,0,1,0,0,0,0], \
[1,0,0,1,1,0,0,0,0,0], \
[1,0,1,0,0,1,0,0,0,0], \
[1,1,0,0,0,0,1,0,0,0], \
[0,0,0,1,0,0,0,0,0,1], \
[1,0,1,0,0,0,0,0,0,0], \
[0,0,1,0,0,1,0,0,0,0], \
[1,0,1,0,0,0,0,0,0,0], \
[1,0,1,1,1,0,0,0,0,0], \
[0,0,0,0,0,1,0,1,0,0], \
[1,1,1,1,0,0,0,0,0,0], \
[1,0,1,0,0,0,0,0,0,0], \
[0,0,1,0,0,1,0,0,0,0], \
[1,1,0,1,0,0,0,0,0,1], \
[1,0,1,0,1,0,0,0,1,0], \
[0,0,0,1,1,0,0,0,0,0], \
[1,0,0,1,0,0,0,0,0,0], \
[1,0,0,0,1,1,0,0,0,0], \
[1,0,0,1,0,0,0,0,0,0]  \
]

#la solución será una matriz de 5 días con 6 tomas en cada día
#ejemplo:
dia1=[tomas[0],tomas[1],tomas[2],tomas[3],tomas[4],tomas[5]]
dia2=[tomas[6],tomas[7],tomas[8],tomas[9],tomas[10],tomas[11]]
dia3=[tomas[12],tomas[13],tomas[14],tomas[15],tomas[16],tomas[17]]
dia4=[tomas[18],tomas[19],tomas[20],tomas[21],tomas[22],tomas[23]]
dia5=[tomas[24],tomas[25],tomas[26],tomas[27],tomas[28],tomas[29]]

solucion = [dia1,dia2,dia3,dia4,dia5]
display(solucion)

[[[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
  [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
  [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
  [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
  [1, 1, 0, 1, 1, 0, 0, 0, 0, 0]],
 [[1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
  [1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
  [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
  [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
  [1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
  [1, 1, 1, 1, 0, 1, 0, 0, 0, 0]],
 [[1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
  [1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
  [1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
  [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
  [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 1, 0, 0, 0, 0]],
 [[1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
  [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
  [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
  [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 1, 0, 0, 0, 0]],
 [[1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
  [1, 0, 1, 0, 1, 0, 0, 0, 1, 0],
  [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
  [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
  [1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
  [1, 0, 0

Según el modelo para el espacio de soluciones<br>
(*)¿Cual es la función objetivo?

(*)¿Es un problema de maximización o minimización?

Respuesta

In [ ]:
#La función objetivo es el coste total de la solución
#defino el coste como la suma de los actores distintos que participan en las tomas de un día
def coste_dia(dia):
    # Aplicar la operación AND bit a bit entre todos los elementos
    return np.sum(np.bitwise_or.reduce(dia, axis=0))
def coste_solucion(solucion):
    return np.sum(np.apply_along_axis(coste_dia, axis=1, arr=solucion))
print(coste_dia(dia1))
print(coste_solucion(solucion))

#Es un problema de minimización de la función objetivo

7
38


Diseña un algoritmo para resolver el problema por fuerza bruta

Respuesta

In [ ]:
#solución de menor coste
mejor_solucion = solucion
mejor_coste=math.inf

Calcula la complejidad del algoritmo por fuerza bruta

Respuesta

In [ ]:
from itertools import permutations
import numpy as np

def generar_combinaciones_iterador(array, dias_grupo,actores_dia):
    for mezcla in permutations(array,len(array)):
        yield(np.array(mezcla).reshape(len(array)//dias_grupo,dias_grupo,actores_dia))

def mejor_planificacion(tomas,tomas_por_dia,actores):
    mejor_solucion=[]
    mejor_coste=math.inf
    i=0
    for iteracion in generar_combinaciones_iterador(tomas,tomas_por_dia,actores):
        coste = coste_solucion(iteracion)
        if coste<mejor_coste:
            mejor_coste=coste
            mejor_solucion = iteracion
            print(iteracion)
        print(coste,mejor_coste)
        i+=1
        print(i)
    solucion = np.zeros((len(mejor_solucion), len(mejor_solucion[0])))
    for i in range(len(mejor_solucion)):
        for j in range(len(mejor_solucion[i])):
            for k in range(len(tomas)):
                if np.array_equal(tomas[k],mejor_solucion[i][j]):
                    if not np.any(solucion == k):
                        solucion[i][j] = k
                        break

    return solucion,mejor_solucion,mejor_coste

In [ ]:
print(mejor_planificacion(tomas,6,10))

a


(*)Diseña un algoritmo que mejore la complejidad del algortimo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta

Respuesta

(*)Calcula la complejidad del algoritmo

Respuesta

Dado que las las soluciones se van a generar a base de permutaciones del conjunto completo de N días, la complejidad será del orden de N!

Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios

Respuesta

In [ ]:
import numpy as np
def tomas_random(tomas, actores):
    #Creo un array vacío
    array = np.empty((tomas, actores), dtype=int)

    #Genero números aleatorios entre 0 y 1 para cada posición del array
    aleatorios = np.random.rand(tomas, actores)

    #Relleno el array con 1 si el número aleatorio es mayor o igual a 0.5, y con 0 si es menor
    array[aleatorios >= 0.5] = 1
    array[aleatorios < 0.5] = 0
    print(array)
    return(array)

Aplica el algoritmo al juego de datos generado

Respuesta

In [ ]:
num_tomas=6
actores=4
tomas_dia=2
tomas_rand=tomas_random(num_tomas,actores)
planificacion_dias, detalle_dias, coste= mejor_planificacion(tomas_rand,tomas_dia,actores)
print('Tomas por día de rodaje:\n',planificacion_dias, '\nActores por día\n',detalle_dias,'\nCoste solución:\n',coste)

[[1 1 1 1]
 [0 0 0 0]
 [1 0 1 1]
 [1 0 1 0]
 [1 1 1 0]
 [0 0 1 1]]
[[[1 1 1 1]
  [0 0 0 0]]

 [[1 0 1 1]
  [1 0 1 0]]

 [[1 1 1 0]
  [0 0 1 1]]]
11 11
1
11 11
2
11 11
3
11 11
4
[[[1 1 1 1]
  [0 0 0 0]]

 [[1 0 1 1]
  [0 0 1 1]]

 [[1 0 1 0]
  [1 1 1 0]]]
10 10
5
10 10
6
11 10
7
11 10
8
10 10
9
10 10
10
11 10
11
11 10
12
11 10
13
11 10
14
10 10
15
10 10
16
11 10
17
11 10
18
10 10
19
10 10
20
11 10
21
11 10
22
11 10
23
11 10
24
10 10
25
10 10
26
10 10
27
10 10
28
[[[1 1 1 1]
  [1 0 1 1]]

 [[0 0 0 0]
  [0 0 1 1]]

 [[1 0 1 0]
  [1 1 1 0]]]
9 9
29
9 9
30
10 9
31
10 9
32
9 9
33
9 9
34
10 9
35
10 9
36
10 9
37
10 9
38
9 9
39
9 9
40
10 9
41
10 9
42
9 9
43
9 9
44
10 9
45
10 9
46
10 9
47
10 9
48
11 9
49
11 9
50
10 9
51
10 9
52
10 9
53
10 9
54
11 9
55
11 9
56
10 9
57
10 9
58
10 9
59
10 9
60
10 9
61
10 9
62
10 9
63
10 9
64
11 9
65
11 9
66
10 9
67
10 9
68
10 9
69
10 9
70
11 9
71
11 9
72
10 9
73
10 9
74
9 9
75
9 9
76
9 9
77
9 9
78
10 9
79
10 9
80
9 9
81
9 9
82
9 9
83
9 9
84
9 9
85
9 9
86
9 9
87
9 9

Enumera las referencias que has utilizado(si ha sido necesario) para llevar a cabo el trabajo

Documentación de python sobre itertools: https://docs.python.org/3/library/itertools.html

Describe brevemente las lineas de como crees que es posible avanzar en el estudio del problema. Ten en cuenta incluso posibles variaciones del problema y/o variaciones al alza del tamaño

Para optimizar un problema de planificación como el de este trabajo, se tendría que buscar una función de selección de las mejores soluciones. En este caso particular, una posible mejora sería tratar de agrupar en un mismo día tomas donde se repitan el máximo número de actores. Una implementación podría ser seleccionar una toma para cada día y luego recorrer el listado clasificando las tomas en el día con mayor coincidencia de actores.